---
title: '6372: Project 1'
author: "Megan Ball, Matt Farrow, Neddy Nyatome"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

## Data Description

## Exploratory Data Analysis

## Objective 1

### Restatement of Problem and the Overall Approach to Solve It

### Model Selection

#### Type of Selection

- LASSO
- RIDGE
- ELASTIC NET
- Stepwise
- Forward
- Backward
- Manual / Intuition
- A mix of all of the above

#### Checking Assumptions

- Residual Plots
- Influential point analysis (Cook’s D and Leverage)

#### Compare Competing Models

Via:  Training and test set split or CV
Possible Metrics: ASE (Required), AIC, BIC, adj R2, are all welcome additions
	
#### Parameter Interpretation (Simple model only)

- Interpretation 
- Confidence Intervals

#### Additional Details on a more complicated regression model 

## Objective 2 Deliverable (see above)
	
Final conclusions from the analyses of Objective 1’s interpretable model and include comments on what model would be recommended if prediction was the only goal (comparing all models considered).  

## Appendix 

- Well-commented SAS/R Code
- Graphics and summary tables (Can be placed in the appendix or in the written report itself.)
